mail.username=anishkumar00138@gmail.com
mail.password=leqjdvwteqmcspxe
mail.smtp.ssl.protocols=TLSv1.2
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
